### PR TITLE
Added Italian Translation

### PR DESCRIPTION
**Pull request by virgafox**
I've added Italian translation. I've copied the directory on my server but it is still in English. Is there something I need to refresh? Thanks

### CODE REVIEW

**Comment by ghost** [comment]
Dear virgafox, thank you for your generous contribution. I merged your commit and tried it out, it seemed to have been working for me, I'm not sure why it isn't for you:
screen shot 2014-01-30 at 12 31 49 pm

**Comment by virgafox** [comment]
so simply uploading the new folder should do the trick? maybe I need to remove and reinstall the plugin...

**Comment by ghost** [comment]
I don't think you need to remove / reinstall, because I didn't... I just
put your new file there and it worked (after having installed the Italian
moodle language pack and changing my settings to Italian).

**Comment by virgafox** [comment]
probably when you installed italian language pack it looked for the italian files, refreshing something. I have removed and reinstalled the plugin and now it is perfect. Thanks for your work.

**Pull request merged**
